#!/usr/bin//env bash
# configures Ubuntu server from localhost and facebook to 127.0.0.2 and 8.8.8.8.8 respectively

oldfile="/etc/hosts"
newfile="$HOME/hosts.new"
sudo cp "$oldfile" "$newfile"
sudo sed -i s/127.0.0.1/127.0.0.2/ "$newfile"
echo "8.8.8.8	facebook.com" >> "$newfile"
sudo cp -f "$newfile" "$oldfile"
